name: Check manifest changes

on:
    pull_request:
        branches-ignore:
            - beta

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository for current commit
              uses: actions/checkout@v2
            - name: Checkout repository in target branch
              uses: actions/checkout@v2
              with:
                  path: "./master-commit"
                  ref: ${{ github.base_ref }}
            - name: Check commit
              run: cd ${{ github.workspace }}/master-commit && git log -1
            - name: Run diff command
              id: diff
              env:
                  CURRENT_COMMIT_SRC_PATH: ${{ github.workspace }}/manifest.json
                  PREVIOUS_COMMIT_SRC_PATH: ${{ github.workspace }}/master-commit/manifest.json
              run: |
                  difference="$(diff $CURRENT_COMMIT_SRC_PATH $PREVIOUS_COMMIT_SRC_PATH | perl -pe 's/\n/%0A/g')"
                  echo "::set-output name=value::$difference"
            - name: Find Comment
              uses: peter-evans/find-comment@v2
              id: find-comment
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  comment-author: "github-actions[bot]"
                  body-includes: "Manifest was updated"
            - name: Create or update comment
              uses: peter-evans/create-or-update-comment@v2
              if: steps.diff.outputs.value != ''
              with:
                  comment-id: ${{ steps.find-comment.outputs.comment-id }}
                  issue-number: ${{ github.event.pull_request.number }}
                  body: |
                      ## ⚠️ The Manifest was updated! Be very careful about this! ([more infos here](https://github.com/phantombuster/web-browser-extension#%EF%B8%8F-manifest-update-warning))

                      ```diff
                      ${{ steps.diff.outputs.value }}
                      ```
                  edit-mode: replace
