name: Sentry release

on:
    push:
        branches:
            - cp-186-add-sentry

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository for current commit
              uses: actions/checkout@v2
            - name: Create Sentry release
              uses: getsentry/action-release@v1
              env:
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                  SENTRY_ORG: phantombuster
                  SENTRY_PROJECT: web-browser-extension
              with:
                  environment: production
