name: Sentry release

on:
    release:
        types: [published]

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository for current commit
              uses: actions/checkout@v3
            - name: Build for sourcemaps
              uses: actions/setup-node@v3
              with:
                  node-version-file: ".nvmrc"
                  cache: "npm"
                  cache-dependency-path: ${{ github.workspace }}/package-lock.json
            - run: |
                  npm ci
                  npm run build:sentry
            - name: Seek manifest version
              id: version
              run: |
                  file="${{ github.workspace }}/manifest.json"
                  version="$(perl -lne 'print $1 if /"version": *"([^"]+)"/' < $file)"
                  echo "value=$version" >> $GITHUB_OUTPUT
            - name: Create Sentry release
              uses: getsentry/action-release@v1
              env:
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                  SENTRY_ORG: phantombuster
                  SENTRY_PROJECT: web-browser-extension
              with:
                  environment: production
                  version: ${{ steps.version.outputs.value }}
                  sourcemaps: ${{ github.workspace }}/dist
